name: Extra Tests Workflow

on:
  pull_request:
    types: [labeled]

jobs:
  run-extra-tests:
    if: contains(github.event.pull_request.labels.*.name, 'extra_test')
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run extra tests
        run: |
          echo "Running extra tests..."
          # Your test commands here
