name: PR Checks

# This specifies when the workflow should run. In this case, it runs on pull request events.
on:
  pull_request:
    types: [opened, synchronize]

# You can also add branches if you want this to run only for specific branches.
# For example:
# on:
#   pull_request:
#     branches:
#       - main
#       - develop
#     types: [opened, synchronize]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [lint, test]  # Ensure linting and tests pass before building

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build